
basepath = "."

locales = [
  "bg",
  "ca",
  "cs",
  "de",
  "es",
  "es-AR",
  "es-ES",
  "et",
  "eu",
  "fi",
  "fr",
  "gd",
  "hu",
  "id",
  "it",
  "ja",
  "ko",
  "nl",
  "pa-IN",
  "pl",
  "ru",
  "sk",
  "ta",
  "tr",
  "sv-SE",
  "zh-CN",
  "zh-TW",
]

# Expose the following branches to localization
# Changes to this list should be announced to the l10n team ahead of time.
branches = [
    "master",
]

[env]

[[paths]]
  reference = "app/src/main/res/values/strings.xml"
  l10n = "app/src/main/res/values-{android_locale}/strings.xml"
