---
trust-domain: mobile
treeherder:
    group-names:
        'beta': 'Nightly-related tasks'
        'debug': 'Builds made for testing'
        'forPerformanceTest': 'Builds made for Raptor and other performance tests'
        'I': 'Docker Image Builds'
        'nightly': 'Nightly-related tasks'
        'nightlyFennec': 'Nightly-related tasks with same APK configuration as Fennec'
        'production': 'Release-related tasks'
        'Rap': 'Raptor tests'
        'Rap-P': 'Raptor power tests'

task-priority: highest

taskgraph:
    register: fenix_taskgraph:register
    repositories:
        mobile:
            name: "Fenix"
    cached-task-prefix: project.mobile.fenix
    decision-parameters: 'fenix_taskgraph:get_decision_parameters'

workers:
    aliases:
        b-android:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
        images:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'images'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: mobile-t-signing
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": mobile-3-signing
                    default: mobile-t-signing
        push-apk:
            provisioner: scriptworker-k8s
            implementation: scriptworker-pushapk
            os: scriptworker
            worker-type: 'mobile-{level}-pushapk'
        t-bitbar.*:
            provisioner: proj-autophone
            implementation: generic-worker
            os: linux-bitbar
            worker-type: 'gecko-{alias}'

scriptworker:
    scope-prefix: project:mobile:fenix:releng
