# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
# This file contains exhaustive information about all the release artifacs that
# are needed within a type of release.
#
# Structure
# --------
# `s3_bucket_paths`       -- prefix to be used per product to correctly access our S3 buckets
# `default_locales`       -- list of locales to be used when composing upstream artifacts or the list of
#                      destinations. If given an empty locale, it uses these locales instead.
# `tasktype_map`          -- mapping between task reference and task type, particularly usefule when
#                      composing the upstreamArtifacts for scriptworker.
# `platform_names`        -- various platform mappings used in reckoning artifacts or other paths
# `default`               -- a default entry, which the mappings extend and override in such a way that
#                      final path full-destinations will be a concatenation of the following:
#                      `s3_bucket_paths`, `destinations`, `locale_prefix`, `pretty_name`
# `from`                  -- specifies the dependency(ies) from which to expect the particular artifact
# `all_locales`           -- boolean argument to specify whether that particular artifact is to be expected
#                      for all locales or just the default one
# `description`           -- brief summary of what that artifact is
# `locale_prefix`         -- prefix to be used in the final destination paths, whether that's for default locale or not
# `source_path_modifier`  -- any parent dir that might be used in between artifact prefix and filename at source location
#                            for example `public/build` vs `public/build/ach/`.
# `destinations`          -- final list of directories where to push the artifacts in S3
# `pretty_name`           -- the final name the artifact will have at destination
# `checksums_path`        -- the name to identify one artifact within the checksums file
# `not_for_platforms`     -- filtering option to avoid associating an artifact with a specific platform
# `only_for_platforms`    -- filtering option to exclusively include the association of an artifact for a specific platform
# `partials_only`         -- filtering option to avoid associating an artifact unless this flag is present
# `update_balrog_manifest`-- flag needed downstream in beetmover jobs to reckon the balrog manifest
# `from_buildid`          -- flag needed downstream in beetmover jobs to reckon the balrog manifest

s3_bucket_paths:
    by-build-type:
        nightly:
            - pub/fenix/nightly
        default:
            - pub/fenix/releases
default_locales:
    - multi
tasktype_map:
    signing: signing
platform_names:
    path_platform: android
    tools_platform: android
    filename_platform: android

default: &default
    from:
        - signing
    all_locales: true
    description: "TO_BE_OVERRIDDEN"
    # Hard coded 'multi' locale
    locale_prefix: '${locale}'
    source_path_modifier:
        by-locale:
            default: '${locale}'
            multi: ''
    checksums_path: "TODO"

mapping:
    arm64-v8a/target.apk:
        <<: *default
        description: "Android package for arm64-v8a"
        pretty_name: fenix-${version}.${locale}.android-arm64-v8a.apk
        destinations:
            - ${folder_prefix}fenix-${version}-android-arm64-v8a
    armeabi-v7a/target.apk:
        <<: *default
        description: "Android package for armeabi-v7a"
        pretty_name: fenix-${version}.${locale}.android-armeabi-v7a.apk
        destinations:
            - ${folder_prefix}fenix-${version}-android-armeabi-v7a
    x86/target.apk:
        <<: *default
        description: "Android package for x86"
        pretty_name: fenix-${version}.${locale}.android-x86.apk
        destinations:
            - ${folder_prefix}fenix-${version}-android-x86
    x86_64/target.apk:
        <<: *default
        description: "Android package for x86_64"
        pretty_name: fenix-${version}.${locale}.android-x86_64.apk
        destinations:
            - ${folder_prefix}fenix-${version}-android-x86_64
