name: Android build PR
on:
  pull_request:
    branches:
      - fork
jobs:
  run-build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.pull_request.title), '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Android SDK with pieces Gradle skips
        run: ./automation/iceraven/install-sdk.sh
      - name: Create version name
        run: echo "VERSION_NAME=$(git describe --tags HEAD)" >> $GITHUB_ENV
      - name: Build forkRelease variant of app
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleForkRelease -PversionName=${{ env.VERSION_NAME }}


  run-testDebug:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.pull_request.title), '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: testDebug


  run-detekt:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.pull_request.title), '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run detekt
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: detekt
      - name: Archive detekt results
        uses: actions/upload-artifact@v2
        with:
          name: detekt report
          path: build/reports/detekt.html


  run-ktlint:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.pull_request.title), '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run ktlint
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: ktlint


  run-lintDebug:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.pull_request.title), '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run lintDebug
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: lintDebug
      - name: Archive lint results
        uses: actions/upload-artifact@v2
        with:
          name: lintDebug report
          path: app/build/reports/lint-results-debug.html
