# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

name: "Fenix - Update Android-Components"

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  main:
    name: "Update Android-Components"
    runs-on: ubuntu-20.04
    steps:
      - name: "Update Android-Components"
        uses: mozilla-mobile/relbot@5.0.2
        if: github.repository == 'mozilla-mobile/fenix'
        with:
          project: fenix
          command: update-android-components
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
